@testitem "Deterministic non-Clifford circuits" tags=[:deterministic] begin

# Truth-table tests: deterministic circuits containing non-Clifford gates.
# The compiled circuit still takes random branches at every gadget measurement,
# so a bit-exact deterministic output on every shot verifies that the Pauli
# correction machinery compensates each random branch correctly. This is the
# regression test for the stabilizer-row sign bug: the recorded row must carry
# the measured (-1)^result sign or the target bit flips on random shots.

using PBCCompiler
using PBCCompiler: Circuit, CircuitOp, ExpHalfPiPauli, parse_input, SimRuntime, StabilizerRuntime
using Moshi.Data: isa_variant
using QuantumClifford: @P_str, Stabilizer, single_z

const FIXTURES = joinpath(@__DIR__, "fixtures")

xgate(q) = ExpHalfPiPauli(P"X", [q])

"""Stabilizer tableau of the basis state |bits⟩: generated by (-1)^bit · Z_q."""
basis_state(bits) = Stabilizer([b ? -single_z(length(bits), q) : single_z(length(bits), q)
                                for (q, b) in enumerate(bits)])

"""
Run `body` on the computational-basis input `bits` under runtime `rt` and return
the classical register. The two prep modes exercise different input paths:
`:gates` prepends X rotations, routing the input through the Clifford-commutation
machinery, while `:tableau` passes the basis state via the `input_state`
argument, routing it through the stabilizer-group sign handling. Both must agree.
"""
function run_on_basis_input(body, bits, mode, rt=SimRuntime())
    if mode == :gates
        prep = CircuitOp.Type[xgate(q) for (q, b) in enumerate(bits) if b]
        state = PBCCompiler.run(Circuit([prep; body]), rt)
    else
        state = PBCCompiler.run(Circuit(copy(body)), rt, basis_state(bits))
    end
    return collect(Bool, state.classical_register[1:length(bits)])
end

# Runtimes that simulate the magic register rather than coining outcomes: a
# deterministic circuit must come out deterministic under each, on every shot.
const SIMULATING_RUNTIMES = (SimRuntime, StabilizerRuntime)

# DummyRuntime is excluded on purpose: it coins every quantum outcome at a fixed
# bias, but later gadget measurements have true conditional probabilities other
# than 1/2 (the magic memory is already partially projected), so it can take
# physically impossible branches that no Pauli correction can compensate —
# deterministic circuits do NOT come out deterministic under DummyRuntime, by
# design. SimRuntime and StabilizerRuntime both simulate the magic register, so
# both are held to the truth table.
@testset "Toffoli truth table ($(nameof(rt)), $mode prep)" for rt in SIMULATING_RUNTIMES,
                                                             mode in (:gates, :tableau)
    ccx = parse_input(joinpath(FIXTURES, "toffoli3.qasm"))
    for a in (false, true), b in (false, true), c in (false, true)
        expected = Bool[a, b, xor(c, a & b)]
        for shot in 1:3
            @test run_on_basis_input(ccx, [a, b, c], mode, rt()) == expected
        end
    end
end

# adder_n4.qasm (QASMBench, Cuccaro-style 1-bit full adder, 7 T gates) maps
# |cin, a, b, d⟩ ↦ |cin, cin⊕a, cin⊕a⊕b, d⊕maj(cin,a,b)⟩ — i.e. q2 ends up
# holding the sum and q3 the carry-out (XORed onto its initial value d).
# Truth table verified against an independent dense statevector simulation.
@testset "adder_n4 truth table ($(nameof(rt)), $mode prep)" for rt in SIMULATING_RUNTIMES,
                                                              mode in (:gates, :tableau)
    adder = parse_input(joinpath(FIXTURES, "adder_n4.qasm"))

    # The fixture is kept verbatim, so it starts with its own input prep
    # `x q[0]; x q[1];`. Verify those are the first two ops, then drop them
    # so the truth-table loop below controls the input state itself.
    @test isa_variant(adder[1], CircuitOp.ExpHalfPiPauli) &&
          adder[1].pauli == P"X" && adder[1].qubits == [1]
    @test isa_variant(adder[2], CircuitOp.ExpHalfPiPauli) &&
          adder[2].pauli == P"X" && adder[2].qubits == [2]
    body = adder[3:end]

    maj(x, y, z) = (x & y) | (x & z) | (y & z)
    for cin in (false, true), a in (false, true), b in (false, true), d in (false, true)
        expected = Bool[cin,
                        xor(cin, a),
                        xor(cin, a, b),
                        xor(d, maj(cin, a, b))]
        for shot in 1:2
            @test run_on_basis_input(body, [cin, a, b, d], mode, rt()) == expected
        end
    end
end

# The unmodified file (input cin=1, a=1, b=0, d=0) must give the QASMBench
# reference output c[0..3] = 1,0,0,1.
@testset "adder_n4 verbatim file ($(nameof(rt)))" for rt in SIMULATING_RUNTIMES
    adder = parse_input(joinpath(FIXTURES, "adder_n4.qasm"))
    state = PBCCompiler.run(Circuit(copy(adder)), rt())
    @test collect(Bool, state.classical_register[1:4]) == Bool[1, 0, 0, 1]
end

end
